### ISSUE TITLE
Reproducibility example crashes

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#136]
When trying to run the reproducibility example from https://github.com/sys-bio/tellurium-examples/blob/master/reproducibilityExample.py on OS X I get the following error:
```
Traceback (most recent call last):

  File "<ipython-input-1-933d8c0b0890>", line 1, in <module>
    runfile('/Users/phantom/devel/src/tellurium-examples/reproducibilityExample.py', wdir='/Users/phantom/devel/src/tellurium-examples')

  File "/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/sitecustomize.py", line 730, in runfile
    execfile(filename, namespace)

  File "/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/sitecustomize.py", line 89, in execfile
    builtins.execfile(filename, *where)

  File "/Users/phantom/devel/src/tellurium-examples/reproducibilityExample.py", line 178, in <module>
    rr.draw(width=300)

  File "/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/tellurium/tellurium.py", line 726, in draw
    diagram = SBMLDiagram(self.getSBML())

  File "/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/tellurium/visualization/sbmldiagram.py", line 59, in __init__
    modifiers=modifiers)

  File "/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/tellurium/visualization/sbmldiagram.py", line 82, in _createGraph
    g = pgv.AGraph(strict=False, directed=True)

AttributeError: 'NoneType' object has no attribute 'AGraph'
```

**Comment by kirichoi** [comment]
Ah, it's the draw() causing problem. I will remove that line.

**Comment by kirichoi** [comment]
Fixed with https://github.com/sys-bio/tellurium-examples/commit/1fd03ddc99d4b6b578fa93301662696f3d52f854

Please check it.

**Comment by 0u812** [comment]
That fixes it. Thanks!
