### ISSUE TITLE
Reproducibility example fails on Mac OS X 10.11

### ISSUE THREAD

**Issue by 0u812** [sys-bio/tellurium#139]
The [reproducibility example] from our example repo for the paper fails on Mac OS X 10.11 when trying to use jinja2. Funny enough, it works on my 10.10 machine. Here is the error message:

```
runfile('/Users/bryan/Downloads/tellurium-examples-master/reproducibilityExample.py', wdir='/Users/bryan/Downloads/tellurium-examples-master')
/private/var/folders/rj/lv87kg257jg86tlgt324168w0000gn/T/tmpIrnQPo_sedml/_te_BorisEJB/experiment1.xml
Traceback (most recent call last):

  File "<ipython-input-7-6a0c26d91ef5>", line 1, in <module>
    runfile('/Users/bryan/Downloads/tellurium-examples-master/reproducibilityExample.py', wdir='/Users/bryan/Downloads/tellurium-examples-master')

  File "/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/sitecustomize.py", line 730, in runfile
    execfile(filename, namespace)

  File "/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/sitecustomize.py", line 89, in execfile
    builtins.execfile(filename, *where)

  File "/Users/bryan/Downloads/tellurium-examples-master/reproducibilityExample.py", line 180, in <module>
    exp.execute(PhrasedMLstr)

  File "/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/tellurium/sedml/tephrasedml.py", line 110, in execute
    execStr = self._toPython(selPhrasedml, workingDir=workingDir)

  File "/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/tellurium/sedml/tephrasedml.py", line 150, in _toPython
    pycode = tesedml.sedmlToPython(expArchive)

  File "/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/tellurium/sedml/tesedml.py", line 132, in sedmlToPython
    return factory.toPython()

  File "/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/tellurium/sedml/tesedml.py", line 346, in toPython
    env = Environment(loader=FileSystemLoader(self.TEMPLATE_DIR),

  File "/Library/Python/2.7/site-packages/jinja2/loaders.py", line 161, in __init__
    if isinstance(searchpath, string_types):

TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```

**Comment by 0u812** [comment]
The error is obviously that it is looking in the wrong directory (`/Library/Python/2.7/site-packages`) for site packages. Trying to figure out why.

**Comment by 0u812** [comment]
`get_python_lib()` result is normal:
```
In [15]: from distutils.sysconfig import get_python_lib

In [16]: get_python_lib()
Out[16]: '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/site-packages'
```

**Comment by 0u812** [comment]
More tests:
```
In [22]: for e in os.environ:
    ...:     print('{}, {}'.format(e,os.environ[e]))
    ...:     
SPYDER_PARENT_DIR, /Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7
UMR_NAMELIST, guidata,guiqwt
QT_API, pyqt
SPYDER_SHELL_ID, 4904876952
PYTHONDONTWRITEBYTECODE, 1
PYTHONHOME, /Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources
LOGNAME, bryan
USER, bryan
HOME, /Users/bryan
PATH, /Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
ARGVZERO, /Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/MacOS/Spyder-Py2
MATPLOTLIB_ION, True
TERM, xterm-color
Apple_PubSub_Socket_Render, /private/tmp/com.apple.launchd.NyKKpH4gwe/Render
ETS_TOOLKIT, qt4
SHLVL, 1
SPYDER_I_PORT, 20128
XPC_FLAGS, 0x0
MATPLOTLIB_BACKEND, Qt4Agg
TMPDIR, /var/folders/rj/lv87kg257jg86tlgt324168w0000gn/T/
EXECUTABLEPATH, /Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/MacOS/Spyder-Py2
UMR_ENABLED, True
IPYTHONDIR, /Users/bryan/.ipython
_PY2APP_LAUNCHED_, 1
SPYDER_AR_STATE, True
SSH_AUTH_SOCK, /private/tmp/com.apple.launchd.2R7N5zcNLy/Listeners
UMR_VERBOSE, True
PYTHONPATH, /Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources
SPYDER_N_PORT, 20129
XPC_SERVICE_NAME, 0
MATPLOTLIBDATA, /Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/mpl-data
SHELL, /bin/bash
GIT_PAGER, cat
SPYDER_INTERPRETER, /Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/MacOS/python
_, /usr/bin/printenv
COLORIZE_SYS_STDERR, True
PYQT_API, 2
SPYDER_AR_TIMEOUT, 2000
RESOURCEPATH, /Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources
CLICOLOR, 1
__CF_USER_TEXT_ENCODING, 0x1F5:0x0:0x0
PWD, /
IGNORE_SIP_SETAPI_ERRORS, False
IPYTHON_KERNEL, True
PAGER, cat
COMMAND_MODE, unix2003
```

**Comment by 0u812** [comment]
Here we go:
```
In [26]: sys.path
Out[26]: 
['',
 '/Library/Python/2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python27.zip',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/plat-darwin',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/plat-mac',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/lib-tk',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/lib-old',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/lib-dynload',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/site-packages.zip',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX 1/Spyder-Py2.app/Contents/Resources/lib/python2.7/site-packages',
 '/usr/local/lib/python2.7/site-packages/IPython/extensions',
 '/Users/bryan/.ipython']
```

**Comment by 0u812** [comment]
That path is in the list on my OS X 10.10 machine, despite the fact that the directory exists.
```
In [9]: sys.path
Out[9]: 
['',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX/Spyder-Py2.app/Contents/Resources',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX/Spyder-Py2.app/Contents/Resources/lib/python27.zip',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX/Spyder-Py2.app/Contents/Resources/lib/python2.7',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX/Spyder-Py2.app/Contents/Resources/lib/python2.7/plat-darwin',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX/Spyder-Py2.app/Contents/Resources/lib/python2.7/plat-mac',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX/Spyder-Py2.app/Contents/Resources/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX/Spyder-Py2.app/Contents/Resources/lib/python2.7/lib-tk',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX/Spyder-Py2.app/Contents/Resources/lib/python2.7/lib-old',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX/Spyder-Py2.app/Contents/Resources/lib/python2.7/lib-dynload',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX/Spyder-Py2.app/Contents/Resources/lib/python2.7/site-packages.zip',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX/Spyder-Py2.app/Contents/Resources/lib/python2.7/site-packages',
 '/Volumes/Tellurium-1.3.5-Spyder-2.3.8-OSX/Spyder-Py2.app/Contents/Resources/lib/python2.7/IPython/extensions',
 '/Users/phantom/.ipython']
```

From Bash:
```
$ ls /Library/Python/2.7/site-packages
README				libantimony.pth			vboxapi-1.0-py2.7.egg-info
antimony			vboxapi				wxredirect.pth
```

**Comment by 0u812** [comment]
I can force this example to run with
```
>>> sys.path.remove('/Library/Python/2.7/site-packages')
>>> sys.path.remove('/usr/local/lib/python2.7/site-packages')
```
Not sure why those directories are there to begin with.

**Comment by 0u812** [comment]
From the [Python documentation](https://docs.python.org/2/tutorial/modules.html#the-module-search-path) on `sys.path`, it appears that the only way to fix this would be to remove all paths from sys.path that do not point to the Tellurium dmg volume.

**Comment by 0u812** [comment]
This problem is Spyder-specific, so I will close it once I can confirm that we can move over to pip (at which point this becomes an upstream bug that we can either try to fix or not, but it will not affect our ability to ship releases)

**Comment by hsauro** [comment]
But will it affect potential reviewers?

Herbert

**Comment by 0u812** [comment]
We'll be using Spyder 3 by the time we submit the manuscript again. I don't know if the problem will still occur with Spyder 3, so I will test it and report here. If it still occurs, I can work with the Spyder people to find out of it is expected behavior or not. If it is a bug, then I will work with them to fix it. (This is essentially what I was thinking when I made my comment above, albeit with a little hesitation because I don't know how much we're going to hype Tellurium on Spyder vs Tellurium on Jupyter in the next manuscript.)

**Comment by 0u812** [comment]
I tried Spyder3 on Bryans Mac and it does not have this issue.

# Installed via .dmg:
```
>>> sys.path
['',
 '/Volumes/Spyder/Spyder.app/Contents/Resources/lib/python3.5/spyder/utils/site',
 '/Volumes/Spyder/Spyder.app/Contents/Resources',
 '/Volumes/Spyder/Spyder.app/Contents/Resources/lib/python35.zip',
 '/Volumes/Spyder/Spyder.app/Contents/Resources/lib/python3.5',
 '/Volumes/Spyder/Spyder.app/Contents/Resources/lib/python3.5/plat-darwin',
 '/Volumes/Spyder/Spyder.app/Contents/Resources/lib/python3.5/lib-dynload',
 '/Volumes/Spyder/Spyder.app/Contents/Resources/lib/python3.5/site-packages.zip',
 '/Volumes/Spyder/Spyder.app/Contents/Resources/lib/python3.5/site-packages',
 '/Volumes/Spyder/Spyder.app/Contents/Resources/lib/python3.5/IPython/extensions',
 '/Users/bryan/.ipython']
```

# Installed via conda:
```
>>> sys.path
['',
 '/Users/bryan/anaconda2/anaconda/lib/python2.7/site-packages/spyder/utils/site',
 '/Users/bryan/anaconda2/anaconda/lib/python27.zip',
 '/Users/bryan/anaconda2/anaconda/lib/python2.7',
 '/Users/bryan/anaconda2/anaconda/lib/python2.7/plat-darwin',
 '/Users/bryan/anaconda2/anaconda/lib/python2.7/plat-mac',
 '/Users/bryan/anaconda2/anaconda/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/bryan/anaconda2/anaconda/lib/python2.7/lib-tk',
 '/Users/bryan/anaconda2/anaconda/lib/python2.7/lib-old',
 '/Users/bryan/anaconda2/anaconda/lib/python2.7/lib-dynload',
 '/Users/bryan/anaconda2/anaconda/lib/python2.7/site-packages/Sphinx-1.4.1-py2.7.egg',
 '/Users/bryan/anaconda2/anaconda/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg',
 '/Users/bryan/anaconda2/anaconda/lib/python2.7/site-packages',
 '/Users/bryan/anaconda2/anaconda/lib/python2.7/site-packages/aeosa',
 '/Users/bryan/anaconda2/anaconda/lib/python2.7/site-packages/IPython/extensions',
 '/Users/bryan/.ipython']
```

**Comment by 0u812** [comment]
Apparently this is not a problem on Spyder 3, so closing.
