### ISSUE TITLE
loadTestModel doesn't seem to work

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#348]
Loading a test model doesn't seem to work:

r = te.loadTestModel('feedback.xml')
Traceback (most recent call last):

  File "<ipython-input-118-bf6a83a81bf0>", line 1, in <module>
    r = te.loadTestModel('feedback.xml')

  File "C:\Tellurium-Winpython\python-2.7.13.amd64\lib\site-packages\tellurium\tellurium.py", line 862, in loadTestModel
    return roadrunner.testing.getRoadRunner(string)

  File "C:\Tellurium-Winpython\python-2.7.13.amd64\lib\site-packages\roadrunner\testing\testfiles.py", line 37, in getRoadRunner
    r.load(data.decode())

  File "C:\Tellurium-Winpython\python-2.7.13.amd64\lib\site-packages\roadrunner\roadrunner.py", line 3559, in load
    self._load(*args)

  File "C:\Tellurium-Winpython\python-2.7.13.amd64\lib\site-packages\roadrunner\roadrunner.py", line 2765, in _load
    return _roadrunner.RoadRunner__load(self, uriOrSBML, options)

NotImplementedError: Wrong number or type of arguments for overloaded function 'RoadRunner__load'.
  Possible C/C++ prototypes are:
    rr::RoadRunner::load(std::string const &,rr::Dictionary const *)
    rr::RoadRunner::load(std::string const &)

**Comment by matthiaskoenig** [comment]
This is a duplicate of 
https://github.com/sys-bio/roadrunner/issues/400
I reported some time ago. Would be great to get this fixed.

**Comment by kirichoi** [comment]
Fixed by commit https://github.com/sys-bio/roadrunner/commit/3a8d9799266a42bca5814de9ac19db05b5a9d5da
