### ISSUE TITLE
importing tellurium causes AttributeError in roadrunner module

### ISSUE THREAD

**Issue by parkersruth** [sys-bio/tellurium#424]
After installing tellurium with pip, `import tellurium` produces the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda/lib/python3.5/site-packages/tellurium/__init__.py", line 14, in <module>
    from .tellurium import (
  File "/anaconda/lib/python3.5/site-packages/tellurium/tellurium.py", line 1029, in <module>
    from .roadrunner import ExtendedRoadRunner
  File "/anaconda/lib/python3.5/site-packages/tellurium/roadrunner/__init__.py", line 2, in <module>
    from .extended_roadrunner import ExtendedRoadRunner
  File "/anaconda/lib/python3.5/site-packages/tellurium/roadrunner/extended_roadrunner.py", line 13, in <module>
    class ExtendedRoadRunner(roadrunner.RoadRunner):
  File "/anaconda/lib/python3.5/site-packages/tellurium/roadrunner/extended_roadrunner.py", line 89, in ExtendedRoadRunner
    dv.__doc__ = roadrunner.ExecutableModel.getStateVector.__doc__
AttributeError: type object 'ExecutableModel' has no attribute 'getStateVector'
```

This is caused by a line in the `ExtendedRoadRunner` class which refers to an undefined module. Commenting out this line allows tellurium to be successfully imported.

The error was encountered in the following context:

- Mac OSX 10.14.2
- Python 3.5.5 (Anaconda distribution)
- Tellurium 2.1.3

**Comment by kirichoi** [comment]
Sorry for the issue. We are in the process of releasing new versions of roadrunner and tellurium and once the new tellurium is released, this issue will go away. You could wait a bit, or get the bleeding edge version from the [develop branch](https://github.com/sys-bio/tellurium/tree/develop).
