### ISSUE TITLE
ODE extraction methods not working

### ISSUE THREAD

**Issue by CiaranWelsh** [sys-bio/tellurium#445]
From the [docs](https://tellurium.readthedocs.io/en/latest/tellurium_methods.html#tellurium.getODEsFromModel) you should be able to 

```

import tellurium as te
r = te.loada ('S1 -> S2; k1*S1; k1=1')
te.getODEsFromModel (r)

```

But I get
```
Warning: species 'S1' has neither initial amount nor concentration set.  Setting initial concentration to 0.0
Warning: species 'S2' has neither initial amount nor concentration set.  Setting initial concentration to 0.0
Traceback (most recent call last):
  File "D:/ReproduciblePaper/BIOMD64/ODE/python_odes.py", line 27, in <module>
    te.getODEsFromModel (r)
  File "C:\Miniconda3\envs\py37\lib\site-packages\tellurium\utils\misc.py", line 118, in getODEsFromModel
    return extractor.toString()
  File "C:\Miniconda3\envs\py37\lib\site-packages\tellurium\utils\misc.py", line 250, in toString
    if not self.model.getSpecies (index).boundary_condition:
  File "C:\Miniconda3\envs\py37\lib\site-packages\tesbml\libsbml.py", line 24321, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Species, name)
  File "C:\Miniconda3\envs\py37\lib\site-packages\tesbml\libsbml.py", line 89, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "C:\Miniconda3\envs\py37\lib\site-packages\tesbml\libsbml.py", line 84, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'

Process finished with exit code 1

```
using tellurium 2.1.5 on Windows 10 and python 3.7

**Comment by hsauro** [comment]
Works in new version of tellurium
