### ISSUE TITLE
Some SED-ML variable names appear not to be supported

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/tellurium#451]
Including this additional SED-ML in the [attached example](https://github.com/sys-bio/tellurium/files/4497617/examples.zip)
```
<dataGenerator id="Mcmin" name="Mcmin">
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <ci> Mcmin </ci>
      </math>
      <listOfVariables>
        <variable id="Mcmin" name="Mcmin" target="/sbml:sbml/sbml:model/sbml:listOfParameters/sbml:parameter[@id=&apos;Mcmin&apos;]" taskReference="BIOMD0000000297_sim"/>
      </listOfVariables>
    </dataGenerator>
```

```
<dataSet id="Mcmin" label="Mcmin" dataReference="Mcmin"/>
```

Causes this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/tellurium", line 11, in <module>
    load_entry_point('Biosimulations-tellurium==2.4.1', 'console_scripts', 'tellurium')()
  File "/usr/local/lib/python3.6/dist-packages/Biosimulations_tellurium/__main__.py", line 51, in main
    app.run()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/foundation.py", line 916, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.6/dist-packages/cement/ext/ext_argparse.py", line 808, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/Biosimulations_tellurium/__main__.py", line 36, in _default
    exec_combine_archive(args.archive, args.out_dir)
  File "/usr/local/lib/python3.6/dist-packages/Biosimulations_tellurium/core.py", line 72, in exec_combine_archive
    factory.executePython()
  File "/usr/local/lib/python3.6/dist-packages/tellurium/sedml/tesedml.py", line 505, in executePython
    exec(compile(code, filename, 'exec'), symbols)
  File "/tmp/te-generated-sedml.py", line 202, in <module>
    Mcmin = __var__Mcnp.nanmin
NameError: name '__var__Mcnp' is not defined
```

**Comment by 0u812** [comment]
Reference: `BIOMD0000000650_sim_2.omex`

**Comment by jonrkarr** [comment]
The above example comes from BIOMD0000000297
