### ISSUE TITLE
Problem with libsbml in tellurium

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#463]
A problem when calling this method, complains about tesbml (libsbml)

Might be a distribution issue or we're not using tesbml anymore and it should reference libsbml.

r = te.loada ('S1 -> S2; k1*S1; k1=0.1; S1 = 1')
te.getODEsFromModel(r)

Traceback (most recent call last):

  File "<ipython-input-151-4f84343b1321>", line 1, in <module>
    te.getODEsFromModel(r)

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\tellurium\utils\misc.py", line 114, in getODEsFromModel
    extractor = ODEExtractor (roadrunnerModel.getSBML())

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\tellurium\utils\misc.py", line 179, in __init__
    self.doc = tesbml.readSBMLFromString (sbmlStr)

AttributeError: module 'tesbml' has no attribute 'readSBMLFromString'

**Comment by evilnose** [comment]
This seems to be the issue that Kiri mentioned in his email, namely that we needed to add an `__init__.py` to the libsbml package directory before building the wheel. These AttributeErrors should also be present in tenuml, tesedml, and sbml2matlab packages, so they would need to be rebuilt too.

I've rebuilt all my wheels on linux per Kiri's instructions and uploaded them to test.pypi.org. I've tested that this error is not present in these wheels. I can upload them to the official index right now, but @luciansmith would you like to confirm that they work first? I can also help if you encounter any issues rebuilding them on windows/mac.
