### ISSUE TITLE
Tellurium plotting not working

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/tellurium#59]
Recent version of roadrunner breaks te.plot functionality.
```
Traceback (most recent call last):

  File "<ipython-input-11-2b32763a921b>", line 1, in <module>
    te.plot(rr, result)

  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\tellurium\tellurium.py", line 501, in plot
    return plotWithLegend(self, result, loc)

  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\tellurium\tellurium.py", line 416, in plotWithLegend
    legendItems = r.selections[1:]

  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\roadrunner\roadrunner.py", line 2493, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, RoadRunner, name)

  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\roadrunner\roadrunner.py", line 78, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)

  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\roadrunner\roadrunner.py", line 73, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)

AttributeError: type object 'object' has no attribute '__getattr__'
```

**Comment by kirichoi** [comment]
Fixed in the updated version of Tellurium
