### ISSUE TITLE
This model crashes roadrunner

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#65]
This model crashes roadruner, why?

import tellurium as te
r = te.loada ('''
J0: A -> D; A*0.05

A = 100
D = 0
''')

result = r.gillespie (0, 10)
r.plot (result)

runfile('C:/Users/hsauro/Documents/untitled2.py', wdir='C:/Users/hsauro/Documents')
Traceback (most recent call last):

  File "<ipython-input-3-6e21463db5eb>", line 1, in <module>
    runfile('C:/Users/hsauro/Documents/untitled2.py', wdir='C:/Users/hsauro/Documents')

  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 711, in runfile
    execfile(filename, namespace)

  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 79, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/hsauro/Documents/untitled2.py", line 10, in <module>
    result = r.gillespie (0, 10)

  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\tellurium\tellurium.py", line 400, in gillespie
    prev = r.integrator.name

  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\roadrunner\roadrunner.py", line 4136, in __getattr__
    return Solver.getValue(self, name)

  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\roadrunner\roadrunner.py", line 3986, in getValue
    return _roadrunner.Solver_getValue(self, key)

RuntimeError: Solver::getValue: invalid key: name

**Comment by 0u812** [comment]
I didn't know we had a method called gillespie. Is it necessary to 
support this method for legacy code, or can we remove it? I ask because 
I'd much rather have users use the standard solver API:

```
r.setIntegrator('gillespie')
r.simulate(0,10)
```

**Comment by 0u812** [comment]
Just saw the email with Jacob, I guess we have to support this. It's a 
real menace that we have all these different ways of doing the same thing...

**Comment by hsauro** [comment]
Yes we need to support r.gillespie, its documented, see:

http://sys-bio.github.io/roadrunner/python_docs/api_reference.html?highlight=gillespie#RoadRunner.RoadRunner.gillespie

Added issue to roadrunner
